### ISSUE TITLE
HM-MOD-RPI-PCB  wird nicht mehr erkannt

### ISSUE THREAD

**Issue by michipi85** [alexreinert/debmatic#84]
Hallo, ich habe das Problem dass sich meine hm-rpc Adapter in Iobroker sich nicht mehr verbunden haben. Hab dann einiges probiert, ohne Erfolg, dass ich nun alles neu aufgesetzt habe.
Nun funktioniert es allerdings immer noch nicht, habe schon den Verdacht, dass das Funkmodul den Geist aufgegeben hat.

Hier mal ein paar Infos.
`debmatic version: 3.49.17-41
Kernel modules: Available
Raw UART dev:   Not available
Rasp.Pi3 UART:  Assigned to GPIO pins
HMRF Hardware:  unknown
HMIP Hardware:  unknown
Board serial:   unknown
Radio MAC:      unknown
SGTIN:          unknown`

bei "sudo systemctl list-dependencies debmatic" ist alles grün, bis auf 
- debmatic-hs485d.service
- debmatic-multimacd.service
- debmatic-rfd.service
- debmatic-setinterfaceclock.timer
- pivccu-dkms.service
- dev-hugepages.mount
- sys-fs-fuse-connections.mount
- systemd-binfmt.service
- systemd-hwdb-update.service
- systemd-machine-id-commit.service
diese sind grau

unter systemctl status debmatic-multimacd kommt inactive
`● debmatic-multimacd.service - debmatic multimacd
   Loaded: loaded (/lib/systemd/system/debmatic-multimacd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2020-01-27 21:04:04 CET; 6min ago

Jan 27 20:12:10 raspberrypi systemd[1]: Condition check resulted in debmatic multimacd being skipped.
Jan 27 21:04:04 raspberrypi systemd[1]: Condition check resulted in debmatic multimacd being skipped.`

genauso bei systemctl status debmatic-rfd
`● debmatic-rfd.service - debmatic rfd
   Loaded: loaded (/lib/systemd/system/debmatic-rfd.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2020-01-27 21:04:05 CET; 9min ago

Jan 27 20:12:10 raspberrypi systemd[1]: Condition check resulted in debmatic rfd being skipped.
Jan 27 21:04:05 raspberrypi systemd[1]: Condition check resulted in debmatic rfd being skipped.`

Kann es an mein Funkmodul liegen oder liegt es vielleicht doch noch wo anders?
Kann ich das Funkmodul irgendwie prüfen?

**Comment by alexreinert** [comment]
Das Problem dürfte hier liegen: `Raw UART dev: Not available`
Was kommt bei
```
sudo dpkg -s pivccu-modules-raspberrypi
cat /boot/config.txt
```

**Comment by michipi85** [comment]
das war das Problem, nabe nun das pivccu modul, nach installiert und läuft auch nun.
Anschließend noch debmatic neu gestartet und jetzt funktioniert wieder alles.
Vielen Dank. :)

**Comment by opu1000** [comment]
Hallo,ich habe das gleiche Problem. Hier der Output bei den obengenanten Kommandos:
sudo dpkg -s pivccu-modules-raspberrypi
Package: pivccu-modules-raspberrypi
Status: install ok installed
Priority: extra
Section: kernel
Maintainer: Alexander Reinert <alex@areinert.de>
Architecture: all
Version: 2.0-15
Depends: raspberrypi-kernel-headers | linux-headers-raspi, pivccu-modules-dkms, bc
Pre-Depends: debconf (>= 0.5) | debconf-2.0
Description: Raspberry Pi kernel modules needed for Homematic
  This package contains the Raspberry Pi kernel needed for Homematic.
Homepage: https://github.com/alexreinert/piVCCU

cat /boot/config.txt
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpu_mem=16

dtoverlay=pivccu-raspberrypi
dtoverlay=pi3-disable-bt


Woran könnte es noch liegen?
